version: '3.8'

services:
    front-end:
        container_name: vue-frontend
        image: uc4official/ui-web:v0.3.0
        build:
            context: .
            dockerfile: Dockerfile
            args: 
                - VUE_APP_API_URL=http://localhost:9000
        ports: 
            - '8080:80'
