version: '3.8'

services:
    front-end:
        container_name: vue-frontend
        image: uc4official/ui-web:latest
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - '8080:80'
