export enum paths {
    WELCOME_PAGE = "/welcome",
    ABOUT_PAGE = "/about",
    LOGIN_PAGE = "/login",
    STUDENT_COURSES = "/courses",
    LECTURER_MY_COURSES = "/course-management",
    ALL_COURSES = "/all-courses",
    ACCOUNT_LIST = "/accounts",
    CREATE_COURSE = "/create-course",
    EDIT_COURSE = "/edit-course",
    PUBLIC_PROFILE = "/user",
    PRIVATE_PROFILE = "/profile",
    HOME = "/",
    CREATE_ACCOUNT = "/create-account",
    EDIT_ACCOUNT = "/edit-account",
    REDIRECT = "/redirect",
    SETTINGS = "/settings",
}
