export enum MutationTypes {
    SET_LOGGEDIN = "SET_LOGGEDIN",
    SET_MODAL = "SET_MODAL",
    SET_USER = "SET_USER",
    SET_DECRYPT_PRIVATE_KEY_MODAL = "SET_DECRYPT_PRIVATE_KEY_MODAL",
    SET_ENCRYPT_PRIVATE_KEY_MODAL = "SET_ENCRYPT_PRIVATE_KEY_MODAL",
    SET_CERTIFICATE = "SET_CERTIFICATE",
    SET_PRIVATE_KEY = "SET_PRIVATE_KEY",
}
