export enum MutationTypes {
    SET_LOGGEDIN = "SET_LOGGEDIN",
    SET_MODAL = "SET_MODAL",
    SET_USER = "SET_USER",
    FORCE_UPDATE_PROFILE_PICTURE = "FORCE_UPDATE_PROFILE_PICTURE",
    FORCE_CLOSE_BURGER_MENU = "FORCE_CLOSE_BURGER_MENU",
}
