export enum MutationTypes {
    SET_LOGGEDIN = "SET_LOGGEDIN",
    SET_MODAL = "SET_MODAL",
    SET_USER = "SET_USER",
    SET_DECRYPT_PRIVATE_KEY_MODAL = "SET_DECRYPT_PRIVATE_KEY_MODAL",
    SET_ENCRYPT_PRIVATE_KEY_MODAL = "SET_ENCRYPT_PRIVATE_KEY_MODAL",
    SET_CERTIFICATE = "SET_CERTIFICATE",
    SET_PRIVATE_KEY = "SET_PRIVATE_KEY",
    FORCE_UPDATE_PROFILE_PICTURE = "FORCE_UPDATE_PROFILE_PICTURE",
    FORCE_CLOSE_BURGER_MENU = "FORCE_CLOSE_BURGER_MENU",
    SET_HAS_CERTIFICATE = "SET_HAS_CERTIFICATE",
}
