# from https://github.com/marketplace/actions/auto-tag

# Will automatically push a tag with the version of our package.json
# Only triggers on pushes to master

name: Create tag and release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - id: step1
      name: Create tag
      uses: Klemensas/action-autotag@stable
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        tag_prefix: "v"
        tag_message: "Please refer to the changelog for details."
    - name: Create Release for Tag
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.step1.outputs.tagname }}
        release_name: Release ${{ steps.step1.outputs.tagname }}
        body: |
          Please refer to [CHANGELOG.md](https://github.com/upb-uc4/ui-web/blob/master/CHANGELOG.md) for details.
        draft: false
        prerelease: true